### PR TITLE
Update giongo.txt

### PR DESCRIPTION
**Pull request by orende**
Recently noticed this sfx being used to represent swiping on touch screens.

### CODE REVIEW

**Comment by Pomax** [comment]
Hmm, weirdly, github claims that your change is a binary file change and refuses to show the diff. Any idea whether you did something different to make the PR show as a full file diff?

**Comment by orende** [comment]
Wow. Not sure what happened that would cause that. Maybe encoding related?
I can try recreating the change.

**Comment by Pomax** [comment]
Hm, probably worth it, I can't seem to coax github into showing it as normal text. If it's a small change, you can probably actually do the work on github itself, which I would imagine "can't go wrong"? (hard to say without knowing what actually went wrong of course, but worth a try?"

**Comment by orende** [comment]
Good idea, I'll try that as soon as time allows.

**Comment by orende** [comment]
As I was making an edit with the web-editor, Github said: "We’ve detected the file encoding as UTF-16LE. When you commit changes we will transcode it to UTF-8." So I guess that's what corrupted the file.

**Pull request closed without merging**
